#!/bin/sh

set -e

remove_divert() {
  if [ ! -z "$(dpkg-divert --list $1)" ]; then
    dpkg-divert --remove --package mx-live-usb-gui --rename \
      --divert $1.distrib $1
  fi
}

if [ "$1" = "remove" ]; then
  remove_divert /usr/local/bin/antix2usb.py
  remove_divert /usr/share/applications/antix/live-usb.desktop
fi
