#!/bin/sh

set -e

check_divert() {
	if [ -z "$(dpkg-divert --list $1)" ]; then
		dpkg-divert --add --package mx-live-usb-gui --rename \
		  --divert $1.distrib $1
	fi
}

if [ "$1" = "install" ] || [ "$1" = "upgrade" ]
then
  check_divert /usr/local/bin/antix2usb.py
  check_divert /usr/share/applications/antix/live-usb.desktop
fi
